"""empty message

Revision ID: 49842a3a5521
Revises: 61b69d8acc17
Create Date: 2021-09-18 22:33:00.315062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49842a3a5521'
down_revision = '61b69d8acc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
